/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logins;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
import progettozoo.Animale;
import progettozoo.DBConnect;
import progettozoo.Habitat;
import progettozoo.Prodotto;
import progettozoo.ProgettoZoo;
import progettozoo.Utente;
import schede.JAggiungiAnimale_Direttore;
import schede.JAggiungiHabitat_Direttore;
import schede.JAggiungiPersonale_Direttore;
import schede.JAggiungiProdotto_Direttore;
import schede.JAggiungiSpecie_Direttore;
import schede.JListaHabitat_Direttore;
import schede.JListaPersonale_Direttore;
import schede.JListaProdotti_Direttore;
import schede.JRimuoviAnimale_Direttore;
import schede.JRimuoviHabitat_Direttore;
import schede.JRimuoviPersonale_Direttore;
import schede.JRimuoviProdotto_Direttore;
import schede.JRimuoviSpecie_Direttore;
import schede.jListaAnimali_Direttore;

/**
 *
 * @author Alberto
 */
public class JDirettore extends javax.swing.JFrame {

    /**
     * Creates new form JDirettore
     */
    public JDirettore() {
        initComponents();
    }
    public JDirettore(Utente user_login) {
        initComponents();
        setTitle("Benvenuto, "+user_login.getNome()+ " " + user_login.getCognome() );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLogout = new javax.swing.JButton();
        jAggiungiPersonale = new javax.swing.JButton();
        jRimuoviPersonale = new javax.swing.JButton();
        jAggiungiAnimale = new javax.swing.JButton();
        jRimuoviAnimale = new javax.swing.JButton();
        jAggiungiHabitat = new javax.swing.JButton();
        jRimuoviHabitat = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jListaanimali = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jAggiungiProdotto = new javax.swing.JButton();
        jRimuoviProdotto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlistahabitat = new javax.swing.JButton();
        jlistapersonale = new javax.swing.JButton();
        jlistaprodotti = new javax.swing.JButton();
        jRimuoviSpecie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Direttore");
        setResizable(false);

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jAggiungiPersonale.setText("Aggiungi Personale");
        jAggiungiPersonale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAggiungiPersonaleActionPerformed(evt);
            }
        });

        jRimuoviPersonale.setText("Rimuovi Personale");
        jRimuoviPersonale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRimuoviPersonaleActionPerformed(evt);
            }
        });

        jAggiungiAnimale.setText("Aggiungi Animale");
        jAggiungiAnimale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAggiungiAnimaleActionPerformed(evt);
            }
        });

        jRimuoviAnimale.setText("Rimuovi Animale");
        jRimuoviAnimale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRimuoviAnimaleActionPerformed(evt);
            }
        });

        jAggiungiHabitat.setText("Aggiungi Habitat");
        jAggiungiHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAggiungiHabitatActionPerformed(evt);
            }
        });

        jRimuoviHabitat.setText("Rimuovi Habitat");
        jRimuoviHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRimuoviHabitatActionPerformed(evt);
            }
        });

        jButton7.setText("Vedi Incassi");

        jListaanimali.setText("Lista Animali");
        jListaanimali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListaanimaliActionPerformed(evt);
            }
        });

        jButton9.setText("Presta Animale");

        jAggiungiProdotto.setText("Aggiungi Prodotto");
        jAggiungiProdotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAggiungiProdottoActionPerformed(evt);
            }
        });

        jRimuoviProdotto.setText("Rimuovi Prodotto");
        jRimuoviProdotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRimuoviProdottoActionPerformed(evt);
            }
        });

        jLabel1.setText("            Gestione Animali");

        jLabel2.setText("           Gestione Habitat");

        jLabel3.setText("          Gestione Personale");

        jLabel4.setText("           Gestione Prodotti");

        jlistahabitat.setText("Lista Habitat");
        jlistahabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlistahabitatActionPerformed(evt);
            }
        });

        jlistapersonale.setText("Lista Personale");
        jlistapersonale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlistapersonaleActionPerformed(evt);
            }
        });

        jlistaprodotti.setText("Lista Prodotti");
        jlistaprodotti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlistaprodottiActionPerformed(evt);
            }
        });

        jRimuoviSpecie.setText("Rimuovi Specie");
        jRimuoviSpecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRimuoviSpecieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlistapersonale, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jAggiungiPersonale, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRimuoviPersonale, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRimuoviAnimale, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jListaanimali, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jAggiungiAnimale, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(79, 79, 79)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRimuoviSpecie, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(72, 72, 72)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jlistahabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jAggiungiHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRimuoviHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(72, 72, 72)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlistaprodotti, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jAggiungiProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRimuoviProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlistapersonale, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlistaprodotti, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jListaanimali, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlistahabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAggiungiHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAggiungiPersonale, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAggiungiProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAggiungiAnimale, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRimuoviPersonale, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRimuoviAnimale, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRimuoviProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRimuoviHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRimuoviSpecie, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        JLogin log = new JLogin();
        log.setLocationRelativeTo(null);
        log.setVisible(true);
        log.close(this);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jRimuoviHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRimuoviHabitatActionPerformed
         JRimuoviHabitat_Direttore rim = new JRimuoviHabitat_Direttore();
                    rim.setLocationRelativeTo(null);
                    rim.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jRimuoviHabitatActionPerformed

    private void jAggiungiPersonaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAggiungiPersonaleActionPerformed
       JAggiungiPersonale_Direttore per = new JAggiungiPersonale_Direttore();
                    per.setLocationRelativeTo(null);
                    per.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jAggiungiPersonaleActionPerformed

    private void jAggiungiAnimaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAggiungiAnimaleActionPerformed
       JAggiungiAnimale_Direttore an = new JAggiungiAnimale_Direttore();
                   an.setLocationRelativeTo(null);
                   an.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jAggiungiAnimaleActionPerformed

    private void jAggiungiHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAggiungiHabitatActionPerformed
        JAggiungiHabitat_Direttore hab = new JAggiungiHabitat_Direttore();
         hab.setLocationRelativeTo(null);
                   hab.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jAggiungiHabitatActionPerformed

    private void jListaanimaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListaanimaliActionPerformed
        jListaAnimali_Direttore lis = new jListaAnimali_Direttore();
         lis.setLocationRelativeTo(null);
                   lis.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jListaanimaliActionPerformed

    private void jRimuoviPersonaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRimuoviPersonaleActionPerformed
      JRimuoviPersonale_Direttore rimpers = new JRimuoviPersonale_Direttore();
      rimpers.setLocationRelativeTo(null);
          rimpers.setVisible(true);
    }//GEN-LAST:event_jRimuoviPersonaleActionPerformed

    private void jRimuoviAnimaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRimuoviAnimaleActionPerformed
       JRimuoviAnimale_Direttore riman = new JRimuoviAnimale_Direttore();
       riman.setLocationRelativeTo(null);
       riman.setVisible(true);
    }//GEN-LAST:event_jRimuoviAnimaleActionPerformed

    private void jAggiungiProdottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAggiungiProdottoActionPerformed
      JAggiungiProdotto_Direttore aggpro= new JAggiungiProdotto_Direttore();
      aggpro.setLocationRelativeTo(null);
      aggpro.setVisible(true);
    }//GEN-LAST:event_jAggiungiProdottoActionPerformed

    private void jRimuoviProdottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRimuoviProdottoActionPerformed
      JRimuoviProdotto_Direttore rimpro= new JRimuoviProdotto_Direttore();
      rimpro.setLocationRelativeTo(null);
      rimpro.setVisible(true);
    }//GEN-LAST:event_jRimuoviProdottoActionPerformed

    private void jRimuoviSpecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRimuoviSpecieActionPerformed
         JRimuoviSpecie_Direttore rimspe= new JRimuoviSpecie_Direttore();
      rimspe.setLocationRelativeTo(null);
      rimspe.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jRimuoviSpecieActionPerformed

    private void jlistapersonaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlistapersonaleActionPerformed
        JListaPersonale_Direttore lisper = new JListaPersonale_Direttore();
        lisper.setLocationRelativeTo(null);
        lisper.setVisible(true);
    }//GEN-LAST:event_jlistapersonaleActionPerformed

    private void jlistahabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlistahabitatActionPerformed
         JListaHabitat_Direttore lishab= new JListaHabitat_Direttore();
       lishab.setLocationRelativeTo(null);
       lishab.setVisible(true);
    }//GEN-LAST:event_jlistahabitatActionPerformed

    private void jlistaprodottiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlistaprodottiActionPerformed
          JListaProdotti_Direttore lispro=new JListaProdotti_Direttore();
       lispro.setLocationRelativeTo(null);
       lispro.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jlistaprodottiActionPerformed

    /**
     * @param args the command line arguments
     */
public void Show_Prodotti_In_JTable(JTable table)
   {
       DBConnect conn=new DBConnect();
       ArrayList<Prodotto> list = conn.listaProdotti();
       DefaultTableModel model = (DefaultTableModel) table.getModel();
       Object[] row = new Object[3];
       
        table.changeSelection(0, 0, false, false);
       for(int i = 0; i < list.size(); i++)
       {
     
           row[0] = list.get(i).getTipo();
           
           row[1] = list.get(i).getPrezzo();
           
           row[2] = list.get(i).getGiacenza();
           
          
                   
           model.addRow(row);
           
       }
    }

   public void Show_Habitat_In_JTable(JTable table)
   {
       DBConnect conn=new DBConnect();
       ArrayList<Habitat> list = conn.selezionaHabitat();
       DefaultTableModel model = (DefaultTableModel) table.getModel();
       Object[] row = new Object[1];
       
        table.changeSelection(0, 0, false, false);
       for(int i = 0; i < list.size(); i++)
       {
     
           row[0] = list.get(i).getHabitat();
                 
           model.addRow(row);
           
       }
    }
    public void Show_Utenti_In_JTable(JTable table)
   {
       ProgettoZoo pz=new ProgettoZoo();
       DBConnect conn=new DBConnect();
       ArrayList<Utente> list = conn.selezionaImpiegato();
       DefaultTableModel model = (DefaultTableModel) table.getModel();
       Object[] row = new Object[8];
       
        table.changeSelection(0, 0, false, false);
       for(int i = 0; i < list.size(); i++)
       {
     
           row[0] = list.get(i).getUsername();
           
           row[1] = list.get(i).getNome();
           
           row[2] = list.get(i).getCognome();
           
           String DataNascita = list.get(i).getData().toString();
                String DataNascita_String = pz.NuovoFormatoData(DataNascita, "yyyy/MM/dd", "dd/MM/yyyy");
           row[3] = DataNascita_String;
           
           row[4] = list.get(i).getResidenza();
           
           row[5] = list.get(i).getIndirizzo();
           
           row[6] = list.get(i).getTelefono();
           
           row[7] = list.get(i).getRuolo();
           
           model.addRow(row);
           
       }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDirettore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDirettore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDirettore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDirettore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDirettore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAggiungiAnimale;
    private javax.swing.JButton jAggiungiHabitat;
    private javax.swing.JButton jAggiungiPersonale;
    private javax.swing.JButton jAggiungiProdotto;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jListaanimali;
    private javax.swing.JButton jRimuoviAnimale;
    private javax.swing.JButton jRimuoviHabitat;
    private javax.swing.JButton jRimuoviPersonale;
    private javax.swing.JButton jRimuoviProdotto;
    private javax.swing.JButton jRimuoviSpecie;
    private javax.swing.JButton jlistahabitat;
    private javax.swing.JButton jlistapersonale;
    private javax.swing.JButton jlistaprodotti;
    // End of variables declaration//GEN-END:variables
}
