/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logins;


import java.util.ArrayList;
import java.util.Objects;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
import progettozoo.Animale;
import progettozoo.DBConnect;
import progettozoo.Visita;
import schede.JSchedaAnimale_Veterinario;

/**
 *
 * @author Alberto
 */
public class JVeterinario extends javax.swing.JFrame {

    /**
     * Creates new form JVeterinario
     */
    public JVeterinario() {
       

        initComponents();
        String[] jTableAnimaliHeaders  = {"Codice Animale","Nome Animale","Specie","Data di Nascita","Genere","Ultima Visita","Salute","Presente"};
        selectmode(jTableAnimali);   
        creaTabella(jTableAnimali, jTableAnimaliHeaders);
        Show_Animali_In_JTable();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAnimali = new javax.swing.JTable();
        jButtonSchedaAnimale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Veterinario");

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jTableAnimali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", ""},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTableAnimali);

        jButtonSchedaAnimale.setText("Scheda Animale");
        jButtonSchedaAnimale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSchedaAnimaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSchedaAnimale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLogout)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogout)
                    .addComponent(jButtonSchedaAnimale))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        JLogin log = new JLogin();
        log.setLocationRelativeTo(null);
        log.setVisible(true);
        log.close(this);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonSchedaAnimaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSchedaAnimaleActionPerformed
        // TODO add your handling code here:
        
        if(!"".equals(getTableSelectedItem(jTableAnimali, "Codice Animale")) )
        {
        JSchedaAnimale_Veterinario sav = new JSchedaAnimale_Veterinario();
        sav.setLocationRelativeTo(null);
        sav.setVisible(true);
        sav.jLabelDisplayNome.setText(getTableSelectedItem(jTableAnimali, "Nome Animale"));
        sav.jLabelDisplaySpecie.setText(getTableSelectedItem(jTableAnimali, "Specie"));
        sav.jLabelDisplayGenere.setText(getTableSelectedItem(jTableAnimali, "Genere"));
        sav.jLabelDisplayNascita.setText(getTableSelectedItem(jTableAnimali, "Data di Nascita"));
        sav.jLabelDisplaySalute.setText(getTableSelectedItem(jTableAnimali, "Salute"));
        sav.jLabelDisplayPresente.setText(getTableSelectedItem(jTableAnimali, "Presente"));
        }
        else JOptionPane.showMessageDialog(null, "Errore: selezionata riga nulla");
        
        
        
        
    }//GEN-LAST:event_jButtonSchedaAnimaleActionPerformed

   
    
    //Restituisce il valore di una certa colonna di una tabella in base alla riga selezionata.
    public String getTableSelectedItem(JTable table, String item)
    {
        String colonna = "";
        String selezione = "";
        int stop = -1;
        ArrayList jTableHeaders = new ArrayList();
        for(int i=0; i<table.getColumnCount(); i++)
        {  
            jTableHeaders.add(i,table.getColumnName(i));         
            if( jTableHeaders.contains(item)){
                    stop = i;
                    colonna = jTableHeaders.get(stop).toString();
                    selezione = getTableValue(table, i);
                    return selezione;
                }
        }
        if(stop == -1) {
            JOptionPane.showMessageDialog(null, "INDICE TABELLA NON TROVATO");}
        return selezione;
    }
        
    
public void selectmode(JTable table)
{
    //SET SELECTION MODE
    table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    ListSelectionModel model=table.getSelectionModel();
    
    //add listener
    model.addListSelectionListener(new ListSelectionListener() {
      
      @Override
      public void valueChanged(ListSelectionEvent e) {
           
        if(e.getValueIsAdjusting())
        {
          return;
        }
        ListSelectionModel lsm=(ListSelectionModel) e.getSource();
        
        if(lsm.isSelectionEmpty())
        {
          JOptionPane.showMessageDialog(null, "Nessuna Selezione");
        }
        /*else{
            String value = getTableValue(table, 0);
            //int selectedRow=lsm.getMinSelectionIndex();
        JOptionPane.showMessageDialog(null, "Selezionata riga "+value);
        }*/
      }
    });
}   

//ritorna il valore della colonna i-esima della riga selezionata nella tabella
    public String getTableValue(JTable table, int column)
    {
        int row = table.getSelectedRow();
        String value = table.getModel().getValueAt(row, column).toString();
        return value;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
            
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JVeterinario().setVisible(true);
            }
        });
    }
    
    //Crea una tabella non modificabile tranne che per la colonna ultima visita
    /*
    Ho fatto così perchè se andavo a modificare la tabella attraverso custom code
    cambiando il valore tornato da isCellEditable(i,c) la tabella diventava invisibile.
    */
    public void creaTabella(JTable table,String[] columnHeaders){
        Object[][] data = {
            {"","","","","","","","",""},
        };
        
        DefaultTableModel tableModel = new DefaultTableModel(data, columnHeaders)
        {
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false //messo così per ricordarmi come si fa per ogni singola cella
            };
            
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
    table.setModel(tableModel);
    }
   
   public void Show_Animali_In_JTable()
   {
       DBConnect conn = new DBConnect();
       ArrayList<Animale> list = conn.animaliList();
       DefaultTableModel model = (DefaultTableModel) jTableAnimali.getModel();
       Object[] row = new Object[8];
       
       for(int i = 0; i < list.size(); i++)
       {
           ArrayList<Visita> visList = conn.visitaList(list.get(i).getId());
           row[0] = list.get(i).getId();
           row[1] = list.get(i).getNome();
           row[2] = list.get(i).getSpecie();
           row[3] = list.get(i).getDataNascita();
           row[4] = list.get(i).getSesso();
           row[5] =  visList.get(0).getDUV(list.get(i).getId());
           /*
           get(0) perchè la data dell'ultima visita viene registrata ogni volta con un solo elemento
           quindi se metto indice i non va bene perchè altrimenti avanza nella lista in elementi non esistenti
           */
           
           if(list.get(i).getSalute() == true ) row[6] = "OK";
           else row[6] = "MALATO";
           
           if(list.get(i).getPresente() == true ) row[7] = "SI";
           else row[7] = "NO";
           
           model.addRow(row);
       }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSchedaAnimale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAnimali;
    // End of variables declaration//GEN-END:variables
}
