/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logins;

import java.sql.*;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
import progettozoo.Animale;
import progettozoo.DBConnect;
import progettozoo.Visita;

/**
 *
 * @author Alberto
 */
public class JVeterinario extends javax.swing.JFrame {

    /**
     * Creates new form JVeterinario
     */
    public JVeterinario() {
       

        initComponents();
        String[] jTableAnimaliHeaders  = {"Nome Animale","Specie","Data di Nascita","Sesso","Ultima Visita","Salute","Presente"};
        rowSelectModel(jTableAnimali);   
        creaTabella(jTableAnimali, jTableAnimaliHeaders);
        Show_Animali_In_JTable();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAnimali = new javax.swing.JTable();
        jButtonSchedaAnimale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Veterinario");

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jTableAnimali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", ""},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTableAnimali);

        jButtonSchedaAnimale.setText("Scheda Animale");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButtonSchedaAnimale)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonSchedaAnimale, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(238, 238, 238)
                .addComponent(jButtonLogout)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        JLogin log = new JLogin();
        log.setLocationRelativeTo(null);
        log.setVisible(true);
        log.close(this);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JVeterinario().setVisible(true);
            }
        });
    }
    
    //Crea una tabella non modificabile tranne che per la colonna ultima visita
    /*
    Ho fatto così perchè se andavo a modificare la tabella attraverso custom code
    cambiando il valore tornato da isCellEditable(i,c) la tabella diventava invisibile.
    */
    public void creaTabella(JTable table,String[] columnHeaders){
        Object[][] data = {
            {"","","","","","",""},
        };
        
        DefaultTableModel tableModel = new DefaultTableModel(data, columnHeaders)
        {
           
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false
            };
            
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
    table.setModel(tableModel);
    }
    
    //Seleziona riga di una tabella anziché la singola cella
    public void rowSelectModel(JTable table)
    {
            
        ListSelectionModel model = table.getSelectionModel();
        model.addListSelectionListener(new ListSelectionListener(){
        
            @Override
            public void valueChanged(ListSelectionEvent e) {
              if(!model.isSelectionEmpty())
                {
                    int selectedRow = model.getMinSelectionIndex();
                    JOptionPane.showMessageDialog(null,"Selezionata la riga: "+selectedRow);
                }
            }
        });
        
    }
   
   public void Show_Animali_In_JTable()
   {
       DBConnect conn = new DBConnect();
       ArrayList<Animale> list = conn.animaliList();
       DefaultTableModel model = (DefaultTableModel) jTableAnimali.getModel();
       Object[] row = new Object[7];
       
       for(int i = 0; i < list.size(); i++)
       {
           ArrayList<Visita> visList = conn.visitaList(list.get(i).getId());
           row[0] = list.get(i).getNome();
           row[1] = list.get(i).getSpecie();
           row[2] = list.get(i).getDataNascita();
           row[3] = list.get(i).getSesso();
           row[4] =  visList.get(0).getDUV();
           /*
           get(0) perchè la data dell'ultima visita viene registrata ogni volta con un solo elemento
           quindi se metto indice i non va bene perchè altrimenti avanza nella lista in elementi non esistenti
           */
           
           if(list.get(i).getSalute() == true ) row[5] = "OK";
           else row[5] = "MALATO";
           
           if(list.get(i).getPresente() == true ) row[6] = "SI";
           else row[6] = "NO";
           
           model.addRow(row);
       }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSchedaAnimale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAnimali;
    // End of variables declaration//GEN-END:variables
}
