/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schede;

import java.awt.*;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import progettozoo.DBConnect;
import progettozoo.ProgettoZoo;
/**
 *
 * @author Roberto
 */
public class JAggiungiPersonale_Direttore extends javax.swing.JFrame {

    /**
     * Creates new form JAggiungiPersonale_Direttore
     */
    public JAggiungiPersonale_Direttore() {
        initComponents();
        
    }
 

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNomePersonale = new javax.swing.JTextField();
        jAggiungiCognome = new javax.swing.JTextField();
        jAggiungiResidenza = new javax.swing.JTextField();
        jAggiungiIndirizzo = new javax.swing.JTextField();
        jAggiungiNumeroTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jAggiungiUser = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jAggiungiPassword = new javax.swing.JPasswordField();
        jRipetiPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jRuolo = new javax.swing.JComboBox<>();
        errorenome = new javax.swing.JLabel();
        errorecognome = new javax.swing.JLabel();
        erroreresidenza = new javax.swing.JLabel();
        erroreindirizzo = new javax.swing.JLabel();
        erroretel = new javax.swing.JLabel();
        erroreuser = new javax.swing.JLabel();
        errorepass = new javax.swing.JLabel();
        errconfpass = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDatanascita = new javax.swing.JTextField();
        erroredata = new javax.swing.JLabel();
        erroreruolo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("        Nome");

        jLabel1.setText("      Cognome");

        jLabel2.setText("         Città");

        jLabel3.setText("       Indirizzo");

        jLabel4.setText("            Telefono");

        jNomePersonale.setForeground(new java.awt.Color(153, 153, 153));
        jNomePersonale.setText("Es.Mario");
        jNomePersonale.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jNomePersonaleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jNomePersonaleFocusLost(evt);
            }
        });
        jNomePersonale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomePersonaleActionPerformed(evt);
            }
        });

        jAggiungiCognome.setForeground(new java.awt.Color(153, 153, 153));
        jAggiungiCognome.setText("Es.Rossi");
        jAggiungiCognome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jAggiungiCognomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jAggiungiCognomeFocusLost(evt);
            }
        });
        jAggiungiCognome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAggiungiCognomeActionPerformed(evt);
            }
        });

        jAggiungiResidenza.setForeground(new java.awt.Color(153, 153, 153));
        jAggiungiResidenza.setText("Es.Roma");
        jAggiungiResidenza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jAggiungiResidenzaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jAggiungiResidenzaFocusLost(evt);
            }
        });
        jAggiungiResidenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAggiungiResidenzaActionPerformed(evt);
            }
        });

        jAggiungiIndirizzo.setForeground(new java.awt.Color(153, 153, 153));
        jAggiungiIndirizzo.setText("Es.via indirizzo 1");
        jAggiungiIndirizzo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jAggiungiIndirizzoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jAggiungiIndirizzoFocusLost(evt);
            }
        });
        jAggiungiIndirizzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAggiungiIndirizzoActionPerformed(evt);
            }
        });

        jAggiungiNumeroTelefono.setForeground(new java.awt.Color(153, 153, 153));
        jAggiungiNumeroTelefono.setText("Es.0147852369");
        jAggiungiNumeroTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jAggiungiNumeroTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jAggiungiNumeroTelefonoFocusLost(evt);
            }
        });
        jAggiungiNumeroTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAggiungiNumeroTelefonoActionPerformed(evt);
            }
        });

        jLabel5.setText("        Username");

        jLabel7.setText("        Password");

        jLabel8.setText("  Conferma Password");

        jAggiungiUser.setForeground(new java.awt.Color(153, 153, 153));
        jAggiungiUser.setText("Campo formato da soli caratteri alfanumerici più  _ e – di lungezza min 3 e max 8");
        jAggiungiUser.setToolTipText("Username formato da soli caratteri alfanumerici più  _ e – di lungezza min 3 e max 15");
        jAggiungiUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jAggiungiUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jAggiungiUserFocusLost(evt);
            }
        });
        jAggiungiUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAggiungiUserActionPerformed(evt);
            }
        });

        jButtonSave.setText("Salva");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonClose.setText("Chiudi");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jAggiungiPassword.setToolTipText("Password che deve contenere un numero, un carattere minuscolo, uno maiuscolo e un carattere speciale tra !@#$% e deve avere lunghezza min 8 e max 20");
        jAggiungiPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jAggiungiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAggiungiPasswordActionPerformed(evt);
            }
        });

        jRipetiPassword.setToolTipText("Password che deve contenere un numero, un carattere minuscolo, uno maiuscolo e un carattere speciale tra !@#$% e deve avere lunghezza min 8 e max 20");
        jRipetiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRipetiPasswordActionPerformed(evt);
            }
        });

        jLabel9.setText("            Ruolo");

        jRuolo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Direttore", "Custode", "Veterinario", "Cassiere" }));
        jRuolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRuoloActionPerformed(evt);
            }
        });

        jLabel10.setText(" Data di Nascita");

        jDatanascita.setForeground(new java.awt.Color(153, 153, 153));
        jDatanascita.setText("Es.22/01/1995");
        jDatanascita.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jDatanascitaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDatanascitaFocusLost(evt);
            }
        });
        jDatanascita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatanascitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorenome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jAggiungiCognome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorecognome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erroreindirizzo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAggiungiResidenza, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAggiungiIndirizzo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNomePersonale, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDatanascita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erroreresidenza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erroredata, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(jButtonClose)
                                .addGap(129, 129, 129))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38))
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(erroreuser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jAggiungiUser, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jAggiungiNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(erroretel, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(errconfpass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jRipetiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jRuolo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jAggiungiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(errorepass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(erroreruolo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(26, 26, 26))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(errorenome, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(erroretel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jAggiungiNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jNomePersonale)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorecognome, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAggiungiCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAggiungiUser, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorepass, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erroredata, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAggiungiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDatanascita, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(errconfpass, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRipetiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAggiungiResidenza, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(erroreindirizzo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(erroreruolo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRuolo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAggiungiIndirizzo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonSave)
                                    .addComponent(jButtonClose))
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(erroreresidenza, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(erroreuser, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    public static boolean check(String regex, String input){
  if (Pattern.matches(regex, input))
    return true;
  else
    return false;
}
  
    private void jAggiungiIndirizzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAggiungiIndirizzoActionPerformed
         String indirizzo= this.jAggiungiIndirizzo.getText();
      // TODO add your handling code here:
    }//GEN-LAST:event_jAggiungiIndirizzoActionPerformed

    private void jNomePersonaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomePersonaleActionPerformed
       String nome= this.jNomePersonale.getText();
       
       
// TODO add your handling code here:
    }//GEN-LAST:event_jNomePersonaleActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
      setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jAggiungiCognomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAggiungiCognomeActionPerformed
       String cognome= this.jAggiungiCognome.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jAggiungiCognomeActionPerformed
   
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
       String nome= this.jNomePersonale.getText();
       String cognome= this.jAggiungiCognome.getText();
       String data=this.jDatanascita.getText();
       String residenza =this.jAggiungiResidenza.getText();
       String indirizzo= this.jAggiungiIndirizzo.getText();
       String telefono= this.jAggiungiNumeroTelefono.getText();
       String username= this.jAggiungiUser.getText();
       String password= this.jAggiungiPassword.getText();
       String rippass= this.jRipetiPassword.getText();
       String ruolo = this.jRuolo.getSelectedItem().toString();
       
        
        
      
          String formnome = "[a-zA-Z ]{1,}";
          String formcog = "[a-zA-Z ]{1,}";
          String fordata="(0[1-9]|1[0-9]|2[0-9]|3[01])[ /](0[1-9]|1[0-2])[/](19|20)[0-9]{2}";
          String formres = "[a-zA-Z ]{1,}";
          String formind = "[a-zA-Z ]{1,}+[ 0-9]{1,}";
          //Numero di telefono formato da soli numeri,minimo 1 e massimo 10
          String formtel = "[0-9]{1,10}";
          //nome utente formato da soli caratteri alfanumerici più  _ e – di lungezza min 3 e max 8
          String formuser ="^[a-z0-9_-]{3,8}$";
          //password che deve contenere un numero, un carattere minuscolo, uno maiuscolo e un carattere speciale tra !@#$% e deve avere lunghezza min 8 e max 20)
          String formpass= "((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%]).{8,16})";
        //questa partecontiene le funzioni per validare il contenuto delle form
           Pattern pattern = Pattern.compile(formnome);
           Pattern pattern1 = Pattern.compile(formcog);
           Pattern pattern2 = Pattern.compile(formres);
           Pattern pattern3 = Pattern.compile(formind);
           Pattern pattern4 = Pattern.compile(formtel);
           Pattern pattern5 = Pattern.compile(formuser);
           Pattern pattern6 = Pattern.compile(formpass);
           Pattern pattern7 = Pattern.compile(fordata);
boolean nom=check(formnome,nome);
boolean cog=check(formcog,cognome);
boolean dat=check(fordata,data);
boolean res=check(formres,residenza);
boolean ind=check(formind,indirizzo);
boolean tel=check(formtel,telefono);
boolean user=check(formuser,username);
boolean pass=check(formpass,password);
boolean rpass=check(password,rippass);

DBConnect conn =new DBConnect();
   String Cod_pers=(this.jAggiungiUser.getText());
   ProgettoZoo pz= new ProgettoZoo();
   Date today =new Date();
Date d= pz.ConvertStringToDate(data, "dd/MM/yyyy");
      java.sql.Date sqlDate = new java.sql.Date(d.getTime());
//nel caso i caratteri inseriti non siano quelli richiesti appare un messaggio d'errore
if(nom== false)
 errorenome.setText("Caratteri non validi");
else
    errorenome.setText("Caratteri validi");
if(cog==false)
    errorecognome.setText("Caratteri non validi");
else
    errorecognome.setText("Caratteri validi");
if(dat==false)
    erroredata.setText("Caratteri non validi");
else if(d.after(today))
     erroredata.setText("Non puoi inserire una data futura");
else
    erroredata.setText("Caratteri validi");
if(res==false)
    erroreresidenza.setText("Caratteri non validi");
else
    erroreresidenza.setText("Caratteri validi");
if(ind==false)
    erroreindirizzo.setText("Caretteri non validi");
else
    erroreindirizzo.setText("Caretteri validi");
if(tel==false)
    erroretel.setText("Caratteri non validi");
else
    erroretel.setText("Caratteri validi");
if(user==false)
    erroreuser.setText("Caratteri non validi");
else
    erroreuser.setText("Caratteri validi");
if(pass==false)
    errorepass.setText("Caratteri non validi");
else
    errorepass.setText("Caratteri validi");
if(rpass==false || pass==false )
    errconfpass.setText("Caratteri non validi");
else
    errconfpass.setText("Caratteri validi");
if(this.jRuolo.getSelectedItem().toString().equals(" "))
    erroreruolo.setText("Non hai inserito il ruolo");
else
    erroreruolo.setText("Caratteri Validi");
 
  
  
  if(nom==true && cog==true && dat==true && res==true && ind==true && tel==true && user==true && pass==true && rpass==true && this.jRuolo.getSelectedItem().toString().equals(" ")==false)
  { 
      if(d.before(today))
      {
       int reply = JOptionPane.showConfirmDialog(null, "Stai inserendo l'utente "+this.jNomePersonale.getText()+" "+this.jAggiungiCognome.getText()+"\n Data di nascita: "+this.jDatanascita.getText()+"\n Città: "+this.jAggiungiResidenza.getText()+"\n Indirizzo: "+this.jAggiungiIndirizzo.getText()+"\n Telefono: "+this.jAggiungiNumeroTelefono.getText()+"\n Username: "+this.jAggiungiUser.getText()+"\n Password: "+this.jAggiungiPassword.getText()+"\n Conferma Password: "+this.jRipetiPassword.getText()+"\n Ruolo: "+this.jRuolo.getSelectedItem().toString(), "Confermare?", JOptionPane.YES_NO_OPTION);
      if (reply == JOptionPane.YES_OPTION)
      {     conn.insertImpiegato(username,nome, cognome,sqlDate, residenza, indirizzo, telefono);
      conn.inserisciUtente(username, password, ruolo);
 
  JOptionPane.showMessageDialog(null, "UTENTE INSERITO CORRETTAMENTE");
   
  if( null!=this.jRuolo.getSelectedItem().toString())
      switch (this.jRuolo.getSelectedItem().toString()) {
          case "Direttore":
              conn.insertDirettore(username);
              break;
          case "Veterinario":
              conn.insertVeterinario(username);
              break;
          case "Custode":
              conn.insertCustode(username);
              break;
          case "Cassiere":
              conn.insertCassiere(username);
              break;
          default:
              break;
      }
   JListaPersonale_Direttore lisper = new JListaPersonale_Direttore();
        lisper.setLocationRelativeTo(null);
        lisper.setVisible(true);
         setVisible(false);
      }
  }else{JOptionPane.showMessageDialog(null, "NON PUOI INSERIRE UNA DATA FUTURA");}
  }else{JOptionPane.showMessageDialog(null, "ALCUNI CAMPI NON SONO INSERITI CORRETTAMENTE");}
       
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jAggiungiResidenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAggiungiResidenzaActionPerformed
      String residenza =this.jAggiungiResidenza.getText();
      
// TODO add your handling code here:
    }//GEN-LAST:event_jAggiungiResidenzaActionPerformed

    private void jAggiungiNumeroTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAggiungiNumeroTelefonoActionPerformed
       String telefono=this.jAggiungiNumeroTelefono.getText();  
      // TODO add your handling code here:
    }//GEN-LAST:event_jAggiungiNumeroTelefonoActionPerformed

    private void jAggiungiUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAggiungiUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAggiungiUserActionPerformed

    private void jAggiungiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAggiungiPasswordActionPerformed
        String password=this.jAggiungiPassword.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_jAggiungiPasswordActionPerformed

    private void jRipetiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRipetiPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRipetiPasswordActionPerformed

    private void jRuoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRuoloActionPerformed
        
      // TODO add your handling code here:
    }//GEN-LAST:event_jRuoloActionPerformed

    private void jDatanascitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatanascitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDatanascitaActionPerformed

    private void jNomePersonaleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNomePersonaleFocusGained
         if(jNomePersonale.getText().equals("Es.Mario"))
         { jNomePersonale.setText("");
         jNomePersonale.setForeground(Color.black);
         }
        else
            jNomePersonale.getText(); 
    }//GEN-LAST:event_jNomePersonaleFocusGained

    private void jNomePersonaleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNomePersonaleFocusLost
         if(jNomePersonale.getText().equals(""))
         { jNomePersonale.setForeground(Color.gray);   
        jNomePersonale.setText("Es.Mario"); }
    }//GEN-LAST:event_jNomePersonaleFocusLost

    private void jAggiungiCognomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAggiungiCognomeFocusGained
         if(jAggiungiCognome.getText().equals("Es.Rossi"))
        {jAggiungiCognome.setText("");
        jAggiungiCognome.setForeground(Color.black);
        }
        else
            jAggiungiCognome.getText();
    }//GEN-LAST:event_jAggiungiCognomeFocusGained

    private void jAggiungiCognomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAggiungiCognomeFocusLost
          if(jAggiungiCognome.getText().equals(""))
          { jAggiungiCognome.setForeground(Color.gray);   
        jAggiungiCognome.setText("Es.Rossi");} 
    }//GEN-LAST:event_jAggiungiCognomeFocusLost

    private void jDatanascitaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDatanascitaFocusGained
           if(jDatanascita.getText().equals("Es.22/01/1995"))
       {jDatanascita.setText("");
        jDatanascita.setForeground(Color.black);
       }
         else
            jDatanascita.getText();
    }//GEN-LAST:event_jDatanascitaFocusGained

    private void jDatanascitaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDatanascitaFocusLost
           if(jDatanascita.getText().equals(""))
           { jDatanascita.setForeground(Color.gray);   
        jDatanascita.setText("Es.22/01/1995");} 
    }//GEN-LAST:event_jDatanascitaFocusLost

    private void jAggiungiResidenzaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAggiungiResidenzaFocusGained
           if(jAggiungiResidenza.getText().equals("Es.Roma"))
           {jAggiungiResidenza.setText("");
            jAggiungiResidenza.setForeground(Color.black);
           }
        else
            jAggiungiResidenza.getText(); 
    }//GEN-LAST:event_jAggiungiResidenzaFocusGained

    private void jAggiungiResidenzaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAggiungiResidenzaFocusLost
            if(jAggiungiResidenza.getText().equals(""))
            { jAggiungiResidenza.setForeground(Color.gray);   
        jAggiungiResidenza.setText("Es.Roma"); }
    }//GEN-LAST:event_jAggiungiResidenzaFocusLost

    private void jAggiungiIndirizzoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAggiungiIndirizzoFocusGained
         if(jAggiungiIndirizzo.getText().equals("Es.via indirizzo 1"))
          {jAggiungiIndirizzo.setText("");
          jAggiungiIndirizzo.setForeground(Color.black);
          }
        else
            jAggiungiIndirizzo.getText();
    }//GEN-LAST:event_jAggiungiIndirizzoFocusGained

    private void jAggiungiIndirizzoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAggiungiIndirizzoFocusLost
             if(jAggiungiIndirizzo.getText().equals(""))
             { jAggiungiIndirizzo.setForeground(Color.gray);   
        jAggiungiIndirizzo.setText("Es.via indirizzo 1"); }
    }//GEN-LAST:event_jAggiungiIndirizzoFocusLost

    private void jAggiungiNumeroTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAggiungiNumeroTelefonoFocusGained
          if(jAggiungiNumeroTelefono.getText().equals("Es.0147852369"))
         {jAggiungiNumeroTelefono.setText("");
          jAggiungiNumeroTelefono.setForeground(Color.black);
         }
        else
            jAggiungiNumeroTelefono.getText(); 
    }//GEN-LAST:event_jAggiungiNumeroTelefonoFocusGained

    private void jAggiungiNumeroTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAggiungiNumeroTelefonoFocusLost
              if(jAggiungiNumeroTelefono.getText().equals(""))
              { jAggiungiNumeroTelefono.setForeground(Color.gray);   
        jAggiungiNumeroTelefono.setText("Es.0147852369");}
    }//GEN-LAST:event_jAggiungiNumeroTelefonoFocusLost

    private void jAggiungiUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAggiungiUserFocusGained
         if(jAggiungiUser.getText().equals("Campo formato da soli caratteri alfanumerici più  _ e – di lungezza min 3 e max 8"))
       {jAggiungiUser.setText("");
        jAggiungiUser.setForeground(Color.black);
       }
        else
            jAggiungiUser.getText();
    }//GEN-LAST:event_jAggiungiUserFocusGained

    private void jAggiungiUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAggiungiUserFocusLost
                if(jAggiungiUser.getText().equals(""))
                {  jAggiungiUser.setForeground(Color.gray);   
        jAggiungiUser.setText("Campo formato da soli caratteri alfanumerici più  _ e – di lungezza min 3 e max 15");}
    }//GEN-LAST:event_jAggiungiUserFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAggiungiPersonale_Direttore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAggiungiPersonale_Direttore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAggiungiPersonale_Direttore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAggiungiPersonale_Direttore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAggiungiPersonale_Direttore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errconfpass;
    private javax.swing.JLabel errorecognome;
    private javax.swing.JLabel erroredata;
    private javax.swing.JLabel erroreindirizzo;
    private javax.swing.JLabel errorenome;
    private javax.swing.JLabel errorepass;
    private javax.swing.JLabel erroreresidenza;
    private javax.swing.JLabel erroreruolo;
    private javax.swing.JLabel erroretel;
    private javax.swing.JLabel erroreuser;
    private javax.swing.JTextField jAggiungiCognome;
    private javax.swing.JTextField jAggiungiIndirizzo;
    private javax.swing.JTextField jAggiungiNumeroTelefono;
    private javax.swing.JPasswordField jAggiungiPassword;
    private javax.swing.JTextField jAggiungiResidenza;
    private javax.swing.JTextField jAggiungiUser;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JTextField jDatanascita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNomePersonale;
    private javax.swing.JPasswordField jRipetiPassword;
    private javax.swing.JComboBox<String> jRuolo;
    // End of variables declaration//GEN-END:variables
}
