/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schede;

import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import logins.JDirettore;
import logins.JVeterinario;
import progettozoo.DBConnect;
import progettozoo.Pasto;
import progettozoo.ProgettoZoo;
import progettozoo.Pulizia;
import progettozoo.Utente;
import static schede.JAggiungiAnimale_Direttore.check;


/**
 *
 * @author Roberto
 */
public class JControlloPulizie_Direttore extends javax.swing.JFrame {
           public static Utente utente = new Utente();
           JVeterinario v= new JVeterinario();
           ProgettoZoo pz= new ProgettoZoo();
           DBConnect conn= new DBConnect();
    /**
     * Creates new form JControlloPulizie_Direttore
     */
    public JControlloPulizie_Direttore(Utente user_log) {
        initComponents();
         utente.setUsername(user_log.getUsername());
        utente.setNome(user_log.getNome());
        utente.setCognome(user_log.getCognome());
        this.jInternalFramePulizie.setVisible(false);
       pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jseldata = new javax.swing.JTextField();
        jConferma = new javax.swing.JButton();
        jChiudi = new javax.swing.JButton();
        jInternalFramePulizie = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePulizie = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("                         SELEZIONA UNA DATA:");

        jConferma.setText("Conferma");
        jConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfermaActionPerformed(evt);
            }
        });

        jChiudi.setText("Chiudi");
        jChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChiudiActionPerformed(evt);
            }
        });

        jInternalFramePulizie.setVisible(true);

        jTablePulizie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePulizie);

        javax.swing.GroupLayout jInternalFramePulizieLayout = new javax.swing.GroupLayout(jInternalFramePulizie.getContentPane());
        jInternalFramePulizie.getContentPane().setLayout(jInternalFramePulizieLayout);
        jInternalFramePulizieLayout.setHorizontalGroup(
            jInternalFramePulizieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePulizieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFramePulizieLayout.setVerticalGroup(
            jInternalFramePulizieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePulizieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jConferma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jChiudi, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jseldata, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jInternalFramePulizie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jInternalFramePulizie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jseldata, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jConferma)
                            .addComponent(jChiudi))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfermaActionPerformed
         
           String data =this.jseldata.getText();
         String fordata ="(0[1-9]|1[0-9]|2[0-9]|3[01])[-](0[1-9]|1[0-2])[-](19|20)[0-9]{2}";
        String fordata2 ="(0[1-9]|1[0-9]|2[0-9]|3[01])[/](0[1-9]|1[0-2])[/](19|20)[0-9]{2}";
        Pattern pattern = Pattern.compile(fordata);
        Pattern pattern2 = Pattern.compile(fordata2);
         boolean dat=check(fordata,data);
         boolean dat2=check(fordata2,data);
        
                 Date d= new Date();
                 Date today=new Date();
   Date d1= pz.ConvertStringToDate(data,"dd-MM-yyyy");
   Date d2= pz.ConvertStringToDate(data,"dd/MM/yyyy");
   
   if(dat)
   {d=d1;}
   else if(dat2)
   {d=d2;}
          java.sql.Date sqlDate = new java.sql.Date(d.getTime());
              if(data.isEmpty())
       {  
        this.jInternalFramePulizie.setVisible(false);
       pack();
       JOptionPane.showMessageDialog(null, "DEVI INSERIRE UNA DATA");}
          else if(!(dat || dat2))
              {  
        this.jInternalFramePulizie.setVisible(false);
       pack();
       JOptionPane.showMessageDialog(null, "CARATTERI NON VALIDI");}

       else if(d.after(today))
           {  
        this.jInternalFramePulizie.setVisible(false);
       pack();
       JOptionPane.showMessageDialog(null, "NON PUOI INSERIRE UNA DATA FUTURA");} 
       
       else{
                 ArrayList<Pulizia> listaPulizie = new ArrayList<Pulizia>();
       Utente[][] utlist=conn.getPulizie(sqlDate, listaPulizie);
           if(listaPulizie.isEmpty())
           {
                this.jInternalFramePulizie.setVisible(false);
       pack();
       JOptionPane.showMessageDialog(null, "NON CI SONO PULIZIE IN QUELLA DATA"); 
           }    else{
        this.jTablePulizie.getTableHeader().setReorderingAllowed(false);
           String[] jTableAnimaliHeaders  = {"Pulizia","Custode","Aiutante 1","Aiutante 2","Stato Pulizia"};
        v.selectmode(this.jTablePulizie);   
        v.creaTabella(this.jTablePulizie, jTableAnimaliHeaders);
        this.jTablePulizie.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        Show_ControlloPulizie_In_JTable(this.jTablePulizie,sqlDate);
        this.jTablePulizie.setVisible(true);
        this.jInternalFramePulizie.setVisible(true);
        pack();
       }
       }
    }//GEN-LAST:event_jConfermaActionPerformed

    private void jChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChiudiActionPerformed
       setVisible(false);
       new JDirettore(utente).setVisible(true);
    }//GEN-LAST:event_jChiudiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JControlloPulizie_Direttore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JControlloPulizie_Direttore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JControlloPulizie_Direttore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JControlloPulizie_Direttore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JControlloPulizie_Direttore(utente).setVisible(true);
            }
        });
    }
        public void Show_ControlloPulizie_In_JTable(JTable table,Date data)
   {
       ProgettoZoo pz=new ProgettoZoo();
       DBConnect conn=new DBConnect();
       ArrayList<Pulizia> listaPulizie = new ArrayList<Pulizia>();
       Utente[][] utlist=conn.getPulizie(data, listaPulizie);
       DefaultTableModel model = (DefaultTableModel) table.getModel();
       Object[] row = new Object[5];
       
        table.changeSelection(0, 0, false, false);
       for(int i = 0; i < listaPulizie.size(); i++)
       {
           String time="";

          
           row[0] = listaPulizie.get(i).getCodice_Gabbia();
           for(int j=0;j<3;j++)
           {
           row[j+1] = utlist[i][j].getNome()+" "+utlist[i][j].getCognome();
          
           
           }
            String stat="";
           
           if(listaPulizie.get(i).getDisponibile())
           {
             stat="NON INIZIATO";
           }else{
               
              
           if(listaPulizie.get(i).getData_Fine_Pulizia().after(listaPulizie.get(i).getData_Inizio_Pulizia()))
           {
             stat="TERMINATO";
           }else{stat="NON TERMINATO";} 
           }
       
           row[4] = stat;
           
         
           
           
           model.addRow(row);
           
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jChiudi;
    private javax.swing.JButton jConferma;
    private javax.swing.JInternalFrame jInternalFramePulizie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePulizie;
    private javax.swing.JTextField jseldata;
    // End of variables declaration//GEN-END:variables
}
