/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schede;


import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import logins.JDirettore;
import progettozoo.Animale;
import progettozoo.DBConnect;
import progettozoo.Habitat;
import progettozoo.ProgettoZoo;
import progettozoo.Utente;
import static schede.JAggiungiAnimale_Direttore.check;


/**
 *
 * @author Roberto
 */
public class JModificaAnimale_Direttore extends javax.swing.JFrame {
    public static Utente utente = new Utente();
    DBConnect conn =new DBConnect();
    ProgettoZoo pz =new ProgettoZoo();
    /**
     * Creates new form JModificaAnimale_Direttore
     */
    public JModificaAnimale_Direttore(Utente user_log) {
        initComponents();
        utente.setUsername(user_log.getUsername());
        utente.setNome(user_log.getNome());
        utente.setCognome(user_log.getCognome());
        
        ArrayList<Animale> list = conn.selezionaAnimaliSpecie();
        for(int i=0;i<list.size();i++)
        {
          this.jselezionaspecie.addItem(list.get(i).getSpecie());
        }
        this.jInternalFrame1.setVisible(false);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonClose = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jGenereAnimale = new javax.swing.JLabel();
        jAggiunginomeanimale = new javax.swing.JTextField();
        jModifica = new javax.swing.JButton();
        jSpecieAnimale = new javax.swing.JLabel();
        jDataAnimale = new javax.swing.JLabel();
        jnostro = new javax.swing.JComboBox<>();
        jNomeAnimale = new javax.swing.JLabel();
        jGenere = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        errorenome = new javax.swing.JLabel();
        erroredata = new javax.swing.JLabel();
        jDatadinascita = new javax.swing.JTextField();

        jselhabitat = new javax.swing.JTextField();
        jselspecie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jselezionaspecie = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jselanim = new javax.swing.JComboBox<>();
        jConferma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonClose.setText("Chiudi");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jInternalFrame1.setVisible(true);

        jLabel4.setText("      Habitat");

        jGenereAnimale.setText("        Genere");

        jModifica.setText("Salva");
        jModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificaActionPerformed(evt);
            }
        });

        jSpecieAnimale.setText("        Specie");

        jDataAnimale.setText("  Data di nascita");

        jnostro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        jNomeAnimale.setText("         Nome");

        jGenere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel2.setText("      Nostro");

        jDatadinascita.setToolTipText("");

        jselhabitat.setEditable(false);

        jselspecie.setEditable(false);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSpecieAnimale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jGenereAnimale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDataAnimale, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jNomeAnimale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(erroredata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorenome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jAggiunginomeanimale)
                    .addComponent(jDatadinascita)
                    .addComponent(jGenere, 0, 190, Short.MAX_VALUE)
                    .addComponent(jselspecie))
                .addGap(37, 37, 37)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jselhabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jnostro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorenome, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jselhabitat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jNomeAnimale, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jAggiunginomeanimale, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpecieAnimale)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jnostro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jselspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGenereAnimale, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGenere, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroredata, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDataAnimale, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDatadinascita, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jLabel3.setText("                            SELEZIONA L'ANIMALE DA MODIFICARE:");

        jselezionaspecie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jselezionaspecieFocusGained(evt);
            }
        });
        jselezionaspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jselezionaspecieActionPerformed(evt);
            }
        });

        jLabel5.setText("SELEZIONA LA SPECIE:");

        jLabel6.setText("SELEZIONA L'ANIMALE:");

        jselanim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jselanimFocusGained(evt);
            }
        });

        jConferma.setText("Conferma");
        jConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfermaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jselezionaspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jselanim, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jConferma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jselezionaspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jselanim, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonClose)
                            .addComponent(jConferma))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        setVisible(false); 
        new JDirettore(utente).setVisible(true);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jselezionaspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jselezionaspecieActionPerformed
       String specie=this.jselezionaspecie.getSelectedItem().toString();
       ArrayList<Animale> lista= new ArrayList<Animale>();
       
       lista=conn.selezionaAnimaliNome(specie);
       if(!lista.isEmpty())
       {  this.jselanim.removeAllItems();
     for(int j = 0; j < lista.size(); j++)
        {
            
            this.jselanim.addItem(lista.get(j).getNome());
            
            
        }}
    }//GEN-LAST:event_jselezionaspecieActionPerformed

    private void jConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfermaActionPerformed
        String specie = this.jselezionaspecie.getSelectedItem().toString();
        String nome = this.jselanim.getSelectedItem().toString();
        String nostro;
        String salute;
        //ArrayList<Animale> animlist =new ArrayList<Animale>();
        Animale an=new Animale();
        Habitat hab=new Habitat();
        ArrayList<Habitat> list =new ArrayList<Habitat>();
          list = conn.selezionaHabitat();
          ArrayList<Animale> lista = conn.selezionaSpecie();
          
         
        an=conn.selezionaAnimale(nome, specie);
        
            this.jAggiunginomeanimale.setText(an.getNome());
       
            
          
       
      
              this.jselspecie.setText(an.getSpecie()); 
            
               
               this.jselhabitat.setText(conn.selezionaHabitatSpecie(this.jselspecie.getText()).getHabitat());
            
            
            
            this.jGenere.setSelectedItem(an.getSesso());
            String DataNascita = an.getDataNascita().toString();
           String DataNascita_String = pz.NuovoFormatoData(DataNascita, "yyyy-MM-dd", "dd-MM-yyyy");
            this.jDatadinascita.setText(DataNascita_String);
            
            if(an.getNostro()== true)
            {    nostro="SI";
            this.jnostro.setSelectedItem(nostro);
            }else{nostro="NO";
             this.jnostro.setSelectedItem(nostro);
            }
            this.jInternalFrame1.setVisible(true);
            setLocationRelativeTo(null);
            pack();
        
    }//GEN-LAST:event_jConfermaActionPerformed

    private void jModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificaActionPerformed
        Animale an=new Animale();
        String specie = this.jselezionaspecie.getSelectedItem().toString();
        String nome = this.jselanim.getSelectedItem().toString();
        String name= this.jAggiunginomeanimale.getText();
        String genere = this.jGenere.getSelectedItem().toString();
        String data= this.jDatadinascita.getText();
        
        name=name.substring(0,1).toUpperCase()+name.substring(1, name.length()).toLowerCase();
        
         String formname = "[a-zA-Z ]{1,30}";
         //inserire la data in formato dd/mm/aaaa (giorno/mese/anno)
         String fordata ="(0[1-9]|1[0-9]|2[0-9]|3[01])[-](0[1-9]|1[0-2])[-](19|20)[0-9]{2}";
         String fordata2 ="(0[1-9]|1[0-9]|2[0-9]|3[01])[/](0[1-9]|1[0-2])[/](19|20)[0-9]{2}";
          Pattern pattern = Pattern.compile(formname);
          Pattern pattern2 = Pattern.compile(fordata);
          Pattern pattern3 = Pattern.compile(fordata2);
        boolean nom=check(formname,name); 
        boolean dat=check(fordata,data);
        boolean dat2=check(fordata2,data);   
         int nostro;
    if(this.jnostro.getSelectedItem()== "SI")
       nostro=1;
   else{nostro=0;}
        
         Date today =new Date();
  Date d= new Date();
   Date d1= pz.ConvertStringToDate(data,"dd-MM-yyyy");
   Date d2= pz.ConvertStringToDate(data,"dd/MM/yyyy");
   if(dat)
   {d=d1;}
   else if(dat2)
   {d=d2;}
      java.sql.Date sqlDate = new java.sql.Date(d.getTime());
      
                     if(nom== false)
 errorenome.setText("Caratteri non validi");
else
    errorenome.setText("Caratteri validi");
      if(dat==false && dat2==false  )
    erroredata.setText("Caratteri non validi");
else if(d.after(today))
 erroredata.setText("Non puoi inserire una data futura");
else
    erroredata.setText("Caratteri validi");
      
        
         if(nom==true  && (dat==true || dat2==true))
         {
              if(d.before(today))
        {int reply = JOptionPane.showConfirmDialog(null, "Vuoi modificare l'animale: "+this.jAggiunginomeanimale.getText()+"\n Specie: "+this.jselspecie.getText()+"\n Sesso: "+this.jGenere.getSelectedItem().toString()+"\n Nato il: "+this.jDatadinascita.getText()+"\n Habitat: "+this.jselhabitat.getText()+"\n Nostro: "+this.jnostro.getSelectedItem().toString(), "Confermare?", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION)
                {  String Cod_Animale=conn.selezionaAnimale(nome, specie).getId();
                   conn.updateAnimale(name, genere, sqlDate,nostro , Cod_Animale);
                    JOptionPane.showMessageDialog(null, "ANIMALE MODIFICATO CORRETTAMENTE");
          setVisible(false);
          new JDirettore(utente).setVisible(true);
                }
        }else{JOptionPane.showMessageDialog(null, "NON PUOI INSERIRE UNA DATA FUTURA");}
         }else{JOptionPane.showMessageDialog(null, "ALCUNI CAMPI NON SONO INSERITI CORRETTAMENTE");}
    }//GEN-LAST:event_jModificaActionPerformed

    private void jselezionaspecieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jselezionaspecieFocusGained
         this.jInternalFrame1.setVisible(false);
         pack();
    }//GEN-LAST:event_jselezionaspecieFocusGained

    private void jselanimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jselanimFocusGained
         this.jInternalFrame1.setVisible(false);
         pack();
    }//GEN-LAST:event_jselanimFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JModificaAnimale_Direttore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JModificaAnimale_Direttore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JModificaAnimale_Direttore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JModificaAnimale_Direttore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JModificaAnimale_Direttore(utente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel erroredata;
    private javax.swing.JLabel errorenome;
    private javax.swing.JTextField jAggiunginomeanimale;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jConferma;
    private javax.swing.JLabel jDataAnimale;
    private javax.swing.JTextField jDatadinascita;
    private javax.swing.JComboBox<String> jGenere;
    private javax.swing.JLabel jGenereAnimale;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jModifica;
    private javax.swing.JLabel jNomeAnimale;
    private javax.swing.JLabel jSpecieAnimale;
    private javax.swing.JComboBox<String> jnostro;
    private javax.swing.JComboBox<String> jselanim;
    private javax.swing.JComboBox<String> jselezionaspecie;
    private javax.swing.JTextField jselhabitat;
    private javax.swing.JTextField jselspecie;
    // End of variables declaration//GEN-END:variables
}
