/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schede;

import java.awt.Toolkit;
import java.awt.event.*;
import java.awt.*;
import logins.JLogin;
import progettozoo.DBConnect;
import logins.JVeterinario;

/**
 *
 * @author Alberto
 */
public class JSchedaAnimale_Veterinario extends javax.swing.JFrame {

    /**
     * Creates new form JSchedaAnimale_Veterinario
     */
    public JSchedaAnimale_Veterinario() {
        initComponents();        
        
        DBConnect conn = new DBConnect();
        JVeterinario v = new JVeterinario();
        String[] jTableVisiteHeaders  = {"Data Visita","Note Visita"};
        v.selectmode(jTableVisite);   
        v.creaTabella(jTableVisite, jTableVisiteHeaders);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jLabelSpecie = new javax.swing.JLabel();
        jLabelHabitat = new javax.swing.JLabel();
        jLabelGenere = new javax.swing.JLabel();
        jLabelDataNascita = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();
        jLabelDisplayNome = new javax.swing.JLabel();
        jLabelDisplaySpecie = new javax.swing.JLabel();
        jLabelDisplayHabitat = new javax.swing.JLabel();
        jLabelDisplayGenere = new javax.swing.JLabel();
        jLabelDisplayNascita = new javax.swing.JLabel();
        jLabelSalute = new javax.swing.JLabel();
        jLabelPresente = new javax.swing.JLabel();
        jButtonNuovaVisita = new javax.swing.JButton();
        jLabelDisplaySalute = new javax.swing.JLabel();
        jLabelDisplayPresente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVisite = new javax.swing.JTable();
        jButtonLeggiNoteVisita = new javax.swing.JButton();
        jLabelCod = new javax.swing.JLabel();
        jLabelDisplayCod = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelNome.setText("Nome:");

        jLabelSpecie.setText("Specie:");

        jLabelHabitat.setText("Habitat:");

        jLabelGenere.setText("Genere:");

        jLabelDataNascita.setText("Data di Nascita:");

        jButtonClose.setText("Chiudi Scheda");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jLabelDisplayNome.setText("-");

        jLabelDisplaySpecie.setText("-");

        jLabelDisplayHabitat.setText("-");

        jLabelDisplayGenere.setText("-");

        jLabelDisplayNascita.setText("-");

        jLabelSalute.setText("Salute Attuale:");

        jLabelPresente.setText("Presente Attualmente:");

        jButtonNuovaVisita.setText("Nuova Visita");

        jLabelDisplaySalute.setText("-");

        jLabelDisplayPresente.setText("-");

        jTableVisite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTableVisite.getTableHeader().setResizingAllowed(false);
        jTableVisite.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableVisite);
        if (jTableVisite.getColumnModel().getColumnCount() > 0) {
            jTableVisite.getColumnModel().getColumn(1).setHeaderValue("Title 2");
        }

        jButtonLeggiNoteVisita.setText("Leggi Note Visita");

        jLabelCod.setText("Codice Animale:");

        jLabelDisplayCod.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNome)
                                .addGap(108, 108, 108)
                                .addComponent(jLabelDisplayNome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPresente)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelDisplayPresente))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSalute)
                                    .addComponent(jLabelGenere)
                                    .addComponent(jLabelHabitat)
                                    .addComponent(jLabelSpecie)
                                    .addComponent(jLabelDataNascita))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDisplaySpecie)
                                    .addComponent(jLabelDisplayHabitat)
                                    .addComponent(jLabelDisplayGenere)
                                    .addComponent(jLabelDisplayNascita)
                                    .addComponent(jLabelDisplaySalute))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabelDisplayCod)
                        .addGap(85, 85, 85)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNuovaVisita)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonLeggiNoteVisita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClose))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCod)
                            .addComponent(jLabelDisplayCod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelDisplayNome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSpecie)
                            .addComponent(jLabelDisplaySpecie))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHabitat)
                            .addComponent(jLabelDisplayHabitat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDisplayGenere)
                            .addComponent(jLabelGenere))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDataNascita)
                    .addComponent(jLabelDisplayNascita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDisplaySalute)
                    .addComponent(jLabelSalute))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jLabelPresente)
                    .addComponent(jButtonNuovaVisita)
                    .addComponent(jLabelDisplayPresente)
                    .addComponent(jButtonLeggiNoteVisita))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here: 
        setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JSchedaAnimale_Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JSchedaAnimale_Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JSchedaAnimale_Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JSchedaAnimale_Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JSchedaAnimale_Veterinario().setVisible(true);
            }
        });
    }    
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonLeggiNoteVisita;
    private javax.swing.JButton jButtonNuovaVisita;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelDataNascita;
    public javax.swing.JLabel jLabelDisplayCod;
    public javax.swing.JLabel jLabelDisplayGenere;
    public javax.swing.JLabel jLabelDisplayHabitat;
    public javax.swing.JLabel jLabelDisplayNascita;
    public javax.swing.JLabel jLabelDisplayNome;
    public javax.swing.JLabel jLabelDisplayPresente;
    public javax.swing.JLabel jLabelDisplaySalute;
    public javax.swing.JLabel jLabelDisplaySpecie;
    private javax.swing.JLabel jLabelGenere;
    private javax.swing.JLabel jLabelHabitat;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPresente;
    private javax.swing.JLabel jLabelSalute;
    private javax.swing.JLabel jLabelSpecie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVisite;
    // End of variables declaration//GEN-END:variables
}
